# Generated by Django 5.1.5 on 2025-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_remove_auctionlistings_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.category'),
        ),
    ]
